### ISSUE TITLE
Kick off Program of Work and Vision for the Risen One Mission Platform

### ISSUE THREAD

**Issue by risen-one-mission** [risen-one-mission/risen-one-mission-platform#2]
## Notes
This is to address the full program of work for the Risen One Mission Platform

## Acceptance Criteria
- [ ] Team is aware of program of work and has a good idea of the Minimal Viable Product (MVP)

## Tasks
- [ ] Kick off meeting with Product Owner, Program Owner, Dev team, Design team and Architect

## Definition of Done
- [ ] All team members have a good idea of the initial direction of the platform
