### ISSUE TITLE
As a site admin, I would like to see site branding reflecting the vision of the website so that it is recognizable and attractive to potential users.

### ISSUE THREAD

**Issue by rebekahhernandez** [risen-one-mission/risen-one-mission-platform#7]
### Background
While getting this site started, there is currently no branding associated. No name or logo or scheme. This story will address that to create wholesome branding so the rest of the site is able to be based on it.

### Acceptance criteria
- [ ] Branding package is created
- [ ] Website url has been purchased

### Tasks
- [ ] Decide on name
- [ ] Decide on color scheme
- [ ] Discuss concept of a logo
- [ ] Branding decisions are recorded in the wiki
- [ ] Branding handbook has been created

### Definition of Done
- [ ] All branding decisions have been made, created and recorded
- [ ] PO Approved
