### ISSUE TITLE
Research Spike - Find A User Auth Service

### ISSUE THREAD

**Issue by Dmac26** [risen-one-mission/risen-one-mission-platform#8]
## Notes
Since we don't want to handle to user authentication processes in-house we need to find a third party service to handle that process.

## Tasks
- [ ] Research third party auth solutions
- [ ] Put together a report on the third party options
- [ ] Present options to the team
- [ ] Once a decision is made on an auth service, create a new card for implementing the service
- [ ] PO approved
